language: python
python:
- '3.6'
- '3.7'
- '3.8'
install:
- pip install --no-cache --ignore-installed -e .
- pip install pyyaml
script:
- pytest
deploy:
  provider: pypi
  user: "__token__"
  password:
    secure: whMfTfIhXof3OTvPFy+gwRwseuY00RlehXNcU4zJ1lfyynToUPiMbxLx2euatoTgnyEMOoORURYTpJYnJVZgWxkcKdXf1IDm9wtbgRYYv3AU91Zi7Zu4Ck0P3owepyiUt0HpqETUlTArBX+yP59T5he3+32q12oYqVygLJInI2e26WOGTlil8f7fvJBWISKE08ina8WI45jST1JgMcOIo2Vv4E895FO7cU/bpbL5rIW0FNyfpkyHuGdBJnmMztkDWscZbVG88yVcAFZWOGfYOfFKbZsXw8MQvwyVNAH8WvcKdUyzwF5EtO6kPMOx45NohzUlCuHdOvS07rFjPOL1NMMZzoUZREP10Yhn7YG8uAV+i2GSVIELGJdGWSulONGSZcUvJk1xomnvz8fHs+4gF3sI0lFdAYnVQcW31teK76eQYJfbSbZ8Mo3rIxbjPYgFzjPSUiEhlglbhGlojqZf0GGVpPCPR1WRY2WqH6s6RclTIQsUk2SwrCe/an0CGJ5mqfESpgrkuKXWi2fMlwlWFmHq0tTlv1qBonpXCcwmj+i+HzhOpHZEO4xR+iMIJNO5McQzLLxMKQevZKWcp5rrt5R7IYhDFc8hb2W7XBLEGAlEvXG3W5/QO9myb5RMzeGaDHptz3+Ylda3R/sUQ1kVHPmpFlAdAnqc7h38ldrDjAs=
  on:
    branch: master
  distributions: "sdist bdist_wheel"
  skip_existing: true