name: Upload the benchmark results
on:
  push:
    branches:
      - master

jobs:
  upload_benchmark_results:
    runs-on: ubuntu-latest
    name: Test out the action in this repository
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Run the benchmark
        run: pytest --benchmark-only --benchmark-json .benchmark_results.json

      - name: Upload the file
        uses: actions/upload-artifact@v2
        with:
          name: benchmark_results
          path: .benchmark_results.json
